// Every photo ships as responsive WebP generated by `npm run images`
// (scripts/optimize-images.sh): /images/<name>-480.webp and /images/<name>-960.webp

export type PhotoName = 'hero' | 'about' | 'fashion' | 'lifestyle' | 'skincare' | 'ugc';

/** Intrinsic size of the 960w file — reserves space and prevents layout shift. */
export const PHOTO_SIZE: Record<PhotoName, { width: number; height: number }> = {
  hero: { width: 960, height: 1280 },
  about: { width: 960, height: 960 },
  fashion: { width: 960, height: 960 },
  lifestyle: { width: 960, height: 960 },
  skincare: { width: 960, height: 960 },
  ugc: { width: 960, height: 960 },
};

export const photoUrl = (name: PhotoName, width: 480 | 960 = 960) =>
  `/images/${name}-${width}.webp`;
