// Every photo ships as responsive WebP generated by `npm run images`
// (scripts/optimize-images.sh): /images/<name>-480.webp and /images/<name>-960.webp.
// Video posters (work-*) come from `npm run videos`, which saves a frame into
// assets/originals/ for the image script to pick up.

export type PhotoName =
  | 'hero'
  | 'portrait'
  | 'bts-1'
  | 'bts-2'
  | 'ig-1'
  | 'ig-2'
  | 'ig-3'
  | 'ig-4'
  | 'ig-5'
  | 'ig-6'
  | 'work-trench'
  | 'work-leather'
  | 'work-studio'
  | 'work-enduro'
  | 'work-picnic'
  | 'work-christening';

const HORIZONTAL_VIDEO = { width: 960, height: 540 }; // 16:9 poster
const INSTAGRAM_TILE = { width: 960, height: 960 }; // square cover from the Instagram grid

/** Intrinsic size of the 960w file — reserves space and prevents layout shift. */
export const PHOTO_SIZE: Record<PhotoName, { width: number; height: number }> = {
  hero: { width: 960, height: 1280 },
  portrait: { width: 960, height: 1693 },
  'bts-1': { width: 960, height: 1440 },
  'bts-2': { width: 960, height: 1440 },
  'ig-1': INSTAGRAM_TILE,
  'ig-2': INSTAGRAM_TILE,
  'ig-3': INSTAGRAM_TILE,
  'ig-4': INSTAGRAM_TILE,
  'ig-5': INSTAGRAM_TILE,
  'ig-6': INSTAGRAM_TILE,
  // Custom covers chosen by the client (photos, not video frames)
  'work-trench': { width: 960, height: 1693 },
  'work-leather': { width: 960, height: 1693 },
  'work-studio': { width: 960, height: 1703 },
  'work-enduro': { width: 960, height: 1440 },
  'work-picnic': HORIZONTAL_VIDEO,
  'work-christening': HORIZONTAL_VIDEO,
};

export const photoUrl = (name: PhotoName, width: 480 | 960 = 960) =>
  `/images/${name}-${width}.webp`;
